version: '3.8'

services:
  auth-service-admin:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: auth-service-admin
    ports:
      - "8089:8089"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - SERVER_PORT=8089
      - KEYCLOAK_URL=https://keycloak.our-galaxy.space
      - KEYCLOAK_REALM=general_realm
      - KEYCLOAK_CLIENT_ID=admin-panel
      - CORS_ALLOWED_ORIGINS=https://admin.our-galaxy.space,http://localhost:5173
    restart: unless-stopped
    networks:
      - monitoring

networks:
  monitoring:
    external: true
    name: monitoring